### ISSUE TITLE
EOF on Docker Login with stable/sonatype Helm chart

### ISSUE THREAD

**Issue by javajon** [travelaudience/nexus-proxy#13]
Getting this EOF error upon _docker login_:
```
$ docker login -u admin -p admin123 kmaster:30313
Error response from daemon: Get https://kmaster:30313/v2/: EOF
```
I'm not fully understanding the solution between the documentation for the proxy, registry and the docker client and the interactions between. **I'm seeking ideas on what might cause this problem.**

**Nexus on Kubernetes Setup**

Kmaster host is a local and _healthy_ K8s cluster, version 1.13.1 setup with Kubeadm with a master and worker node (Mac w/ Parallels). The stable/sonatype Helm chart, version sonatype-nexus-1.15.0, was applied with this command:

`helm install stable/sonatype-nexus --namespace nexus --name nexus -f nexus-values.yaml`

The values file is below. Nexus and its UI runs fine and is _healthy_.

Through the UI a "docker (hosted)" repository was added and configured with:
```
Name: containers
Format: docker
Type: hosted
URL: http://kmaster:30313/repository/containers/
Online: checked
HTTP: 30313
HTTPS: unchecked
Force basic authentication: checked
Enable Docker V1 API: checked
```
The helm chart values applied in nexus-values.yaml reads as:
```
statefulset:
  enabled: false

replicaCount: 1
deploymentStrategy: {}

nexus:
  imageName: quay.io/travelaudience/docker-nexus
  imageTag: 3.14.0
  imagePullPolicy: IfNotPresent
  env:
    - name: install4jAddVmParams
      value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
  resources: {}
  dockerPort: 5003
  nexusPort: 8081
  service:
    type: NodePort
  podAnnotations: {}
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    path: /
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    path: /
  hostAliases: []

nexusProxy:
  enabled: true
  imageName: quay.io/travelaudience/docker-nexus-proxy
  imageTag: 2.4.0
  imagePullPolicy: IfNotPresent
  port: 8080
  targetPort: 8080
  env:
    nexusDockerHost: kmaster
    nexusHttpHost: kmaster
    enforceHttps: false
    cloudIamAuthEnabled: false
  resources: {}

persistence:
  enabled: false

nexusBackup:
  enabled: false

ingress:
  enabled: false

tolerations: []

config:
  enabled: false

deployment:
  annotations: {}
  initContainers:
  postStart:
    command:    # '["/bin/sh", "-c", "ls"]'
  additionalContainers:
  additionalVolumes:

secret:
  enabled: false

service:
  enabled: false
```

**Comment by javajon** [comment]
Docker by default communicates to a container registry with https/TLS and in this case port 30313, a NodePort on Kubernetes, is not TLS enabled. Therefore, the protocols do no match and probably causes the EOF.  

Adding this 
```
{
  "insecure-registries" : ["master:30313"]
}
```
to /etc/docker/daemon.json  and restarting the docker daemon then gives this 404.

```
docker login -u admin -p admin123 kmaster:30313
Error response from daemon: login attempt to http://kmaster:30313/v2/ failed with status: 404 Not Found
```

[Granted, ingress is the was to go.](https://oteemo.com/2017/12/12/think-nodeport-kubernetes/)  However, for testing, I'm soliciting for steps on getting this to work with NodePort.

**Comment by pires** [comment]
You should probably disable Docker API V1.

**Comment by jeff-knurek** [comment]
@javajon I've made the following assumptions about the current setup you have, based on the info provided:

The port `30313`. That's the NodePort that directs traffic through the `nexus` service to the nexus pod via the labels defined in the selector. And the target port of the nexus service is still `8080`, which directs traffic to the `nexusProxy` pod. 

And the `nexusProxy` container has the env variable to then proxy docker traffic with:
```
    - name: UPSTREAM_DOCKER_PORT
      value: "5003"
    - name: NEXUS_DOCKER_HOST
      value: kmaster

    - name: NEXUS_HTTP_HOST
      value: kmaster
    - name: UPSTREAM_HTTP_PORT
      value: "8081"
```

And the `nexus` container has the following port config:
```
    ports:
    - containerPort: 5003
      name: nexus-docker-g
    - containerPort: 8081
      name: nexus-http
```
----
Now, I'm not an expert on this, but if you're calling `docker login kmaster:30313`, I'm not really sure how the traffic is supposed to be forwarded to the nexus container. I know next to nothing about the docker login protocol, and my understanding of the `nexus-proxy` is rudimentary, but I think the problem definitely lies there in your current configuration. 

Maybe the solution is as simple as changing the 
```
nexus:
  dockerPort: 5003
```
in your values file? _(that value changes both `containerPort` & `UPSTREAM_DOCKER_PORT`)_
