### ISSUE TITLE
How to disable nexus proxy ?

### ISSUE THREAD

**Issue by KOSSOKO** [travelaudience/nexus-proxy#21]
First of all, reading this can help understanding that i'm not the only one having this need : [](https://github.com/helm/charts/issues/5385)

Hello all. First happy new year :grinning:

I found a nexus chart for Goole Kubernetes Engine here : https://github.com/helm/charts/tree/master/stable/sonatype-nexus

By default, the type service created is `NodePort` , so In update the values.yml from `NodePort` to `LoadBalancer`

```
dockerPort: 5003
nexusPort: 8081
  service:
    # type: NodePort
    type: LoadBalancer
```

Then I installed the chart using this command :

```
helm install --name gara-nexus sonatype-nexus/
```

GKE generates an external IP adress for the service, running on the port 8080. When I try to got this IP, I got the error :

> Invalid host. To browse Nexus, click here/. To use the Docker registry, point your client at < nil >.

I logs the nexus-proxy deployment and have this error :

> [io.netty.util.internal.MacAddressUtil] Failed to find a usable hardware address from the network interfaces; using random bytes: 63:86:20:76:be:a5:7e:7f 2019-12-30 21:43:28,182 [INFO ] [vert.x-eventloop-thread-0] [com.travelaudience.nexus.proxy.BaseNexusProxyVerticle] Listening at 0.0.0.0:8080.

Here: [Run nexus in kubernetes cluster using helm](https://stackoverflow.com/questions/52274286/run-nexus-in-kubernetes-cluster-using-helm) there is an answer saying that the workaround is to change:

```
nexusProxy:
  imageName: quay.io/travelaudience/docker-nexus-proxy
  imageTag: 2.3.0
  imagePullPolicy: IfNotPresent
  port: 8080
  env:
    nexusDockerHost: 
    nexusHttpHost: 
    enforceHttps: false
    cloudIamAuthEnabled: false
```

with

```
nexusProxy:
  imageName: quay.io/travelaudience/docker-nexus-proxy
  imageTag: 2.3.0
  imagePullPolicy: IfNotPresent
  port: 8080
  env:
    nexusDockerHost: 127.0.0.1
    nexusHttpHost: 127.0.0.1
    enforceHttps: false
    cloudIamAuthEnabled: false
```

I changed it, but result is the same.
I generated a static ip from my gcp console, but still can't acess to the dashboard.

Please how could I correctly configure it and access to the nexus UI? I don't want to use docker-proxy.  I don't have a dns for the for the moment.
I spent one week without success.

Thanks in advance
