### ISSUE TITLE
Using Nexus npm proxy results in invalid http responses

### ISSUE THREAD

**Issue by ThYpHo0n** [travelaudience/nexus-proxy#26]
I tried using nexus-proxy in the context of the oteemo helm chart (https://github.com/Oteemo/charts/tree/master/charts/sonatype-nexus)
and it resulted in the issue that during npm installs I get invalid http responses:
`ERROR  request to https://nexus.company.com/repository/npm-public/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz failed, reason: Parse Error: Content-Length can't be present with chunked encoding`

My helm chart values to reproduce:
```yaml
...
ingress:
  enabled: true
  path: /*
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: my-static-ip
  tls:
    enabled: true
    secretName: wildcard-cert
nexusProxy:
  env:
    nexusHttpHost: nexus.company.com
    nexusDockerHost: containers.company.com
    enforceHttps: true
...
```
Other proxy repos like maven are working fine though and also the webinterface of Nexus is working as expected, therefore I think it has to be something specific to the npm proxy repository.
